version: '3.5'

services:
  postgres:
    container_name: pgdb
    image: postgres:latest
    environment:
      POSTGRES_USER: pgadm
      POSTGRES_PASSWORD: pgmadmin
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local
